services:
  zeronat:
    image: ${ZERONAT_IMAGE:-ghcr.io/paltaio/zeronat:latest}
    container_name: zeronat
    network_mode: host
    restart: unless-stopped
    env_file: .env
    volumes:
      - /etc/zeronat/data:/etc/zeronat/data
    command: ${ZERONAT_ARGS}
